name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  fabian-rosenthal:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fabian-rosenthal
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]
            - cwd: ./fabian-rosenthal
      - name: Check code format
        run: pnpm run format:check
      - name: Build site
        run: pnpm run build
