name: "[fabian-rosenthal] CI"

on:
  #push:
  #  branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "fabian-rosenthal/**"

jobs:
  fabian-rosenthal:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fabian-rosenthal
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check code format
        run: pnpm run format:check
      # Vercel builds preview anyway
      #- name: Build site
      #  run: pnpm run build
