name: Node CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]
      - name: Check code format
        run: pnpm run format:check
      - name: Build site
        run: pnpm run build
